# ┌───────────────────────────────────────────────────────────┐
# │ 1. Build settings                                         │
# └───────────────────────────────────────────────────────────┘
[build]
  command   = "npm run build"        # your build command (e.g. "next build")
  publish   = ".next"                # for Netlify’s Next.js plugin, or use "out" if you export
  functions = "netlify/functions"    # where your fetchFlights.js lives

# ┌───────────────────────────────────────────────────────────┐
# │ 2. Next.js support (requires @netlify/plugin-nextjs)     │
# └───────────────────────────────────────────────────────────┘
[[plugins]]
  package = "@netlify/plugin-nextjs"

# ┌───────────────────────────────────────────────────────────┐
# │ 3. Local development settings                            │
# └───────────────────────────────────────────────────────────┘
[dev]
  framework = "next"                 # lets Netlify Dev know you’re using Next.js
  command   = "npm run dev"
  port      = 8888

[dev.functions]
  directory = "netlify/functions"
